name: Continuous Deployment for Staging

# Controls when the action will run.
on:
  # Triggers the workflow on push or pull request events but only for the develop branch
  pull_request:
    branches: [develop]
    types: [closed]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "deploy"
  deploy:
    if: github.event.pull_request.merged == true
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Runs a set of commands using the runners shell
      - name: work around permission issue
        run: git config --global --add safe.directory /var/www/html
      - name: Deploy WellnessPlus Staging
        uses: appleboy/ssh-action@v0.1.2
        with:
          host: ${{ secrets.STAGING_SSH_HOST }} #server IP address.
          username: ${{ secrets.SSH_USERNAME }} #user for the server.
          password: ${{ secrets.STAGING_SSH_PASSWORD }} #private SSH password of the server.


          script: |
            cd /var/www/html
            git config --global user.name "retailar"
            git config --global user.email "retailartech@gmail.com"
            git pull https://retailar:${{ secrets.RETAILAR_PAT }}@github.com/HazonTechnologies/wellness_patient_backend.git develop
            composer update
            composer install
            php artisan optimize:clear
            php artisan config:cache
            php artisan migrate --no-interaction
            echo 'Deployed Successfully to Digital Ocean.'